# command line: sgcn.py

config: /ssd/xyliu/cvTooBox/pose_track/lighttrack/sgcn/graph/config/inference.yaml
device:
- 0
ignore_weights: []
model: graph.gcn_utils.gcn_model.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: PoseTrack
        strategy: spatial
    in_channels: 2
    num_class: 128
pose_detector: 0
print_log: true
save_log: true
use_gpu: false
video_path: data/demo/video.mp4
weights: /home/xyliu/cvToolBox/pose_track/lighttrack/weights/GCN/epoch210_model.pt
work_dir: ./work_dir/tmp
